# Generated by Django 4.2.5 on 2023-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(max_length=100)),
                ('font_size', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Texteditor',
        ),
    ]
