# Generated by Django 4.2.5 on 2023-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditorapp', '0002_savedtext_delete_texteditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtext',
            name='font_family',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='savedtext',
            name='font_size',
            field=models.CharField(max_length=250),
        ),
    ]
